[package]
name = "i3status-rs"
version = "0.9.0"
authors = ["Kai Greshake <development@kai-greshake.de>",
           "Contributors on GitHub (https://github.com/greshake/i3status-rust/graphs/contributors)"]

[dependencies]
chrono = "0.4"
lazy_static = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
clap = "2.25"
uuid = { version = "0.5", features = ["v4"] }
dbus = "0.5.3"
regex = "0.2"
nix = "0.8.1"
i3ipc = "0.8.2"
num = "0.1.39"
chan = "0.1.19"
inotify = "0.5.0"
mailparse = "0.6.0"
# Used only in debug build mode
# for profiling blocks
cpuprofiler = "0.0.3"
progress = "0.2"
